"""Autonomous Model Context Protocol (MCP) Server Generator.

Enables Micro-AGI to autonomously synthesize, compile, and deploy standalone
production-ready MCP servers for custom APIs, tools, databases, and services.
"""

from __future__ import annotations
from dataclasses import dataclass
import json
import os
from typing import Any, Dict, List, Optional


@dataclass
class ToolSpec:
    name: str
    description: str
    parameters: Dict[str, Dict[str, str]]  # param_name -> {"type": "...", "description": "..."}
    implementation_code: str


class MCPGenerator:
    """Synthesizes complete, runnable Python Model Context Protocol servers."""

    @staticmethod
    def generate_server_script(
        server_name: str,
        tools: List[ToolSpec],
        output_file_path: Optional[str] = None,
    ) -> str:
        """Generates self-contained, executable MCP Server Python script."""
        template_parts = [
            f'"""Autonomous MCP Server: {server_name}',
            'Generated by Micro-AGI Cognitive Architecture.',
            'Complies with Model Context Protocol JSON-RPC 2.0 Stdio Specification.',
            '"""',
            '',
            'import sys',
            'import json',
            'from typing import Any, Dict',
            '',
        ]

        # Generate tool implementation functions
        for tool in tools:
            param_names = list(tool.parameters.keys())
            param_sig = ", ".join(param_names)
            template_parts.append(f"def {tool.name}({param_sig}):")
            # Indent implementation code
            for line in tool.implementation_code.strip().split("\n"):
                template_parts.append(f"    {line}")
            template_parts.append("")

        # Generate Tool Schemas
        template_parts.append("TOOLS_SCHEMA = [")
        for tool in tools:
            schema = {
                "name": tool.name,
                "description": tool.description,
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        p_name: {
                            "type": p_info.get("type", "string"),
                            "description": p_info.get("description", ""),
                        }
                        for p_name, p_info in tool.parameters.items()
                    },
                    "required": list(tool.parameters.keys()),
                },
            }
            template_parts.append(f"    {json.dumps(schema)},")
        template_parts.append("]")
        template_parts.append("")

        # Generate Server Dispatch Loop
        template_parts.extend([
            "def handle_message(msg: Dict[str, Any]) -> Dict[str, Any]:",
            '    req_id = msg.get("id")',
            '    method = msg.get("method")',
            '    params = msg.get("params", {})',
            '',
            '    if method == "initialize":',
            '        return {',
            '            "jsonrpc": "2.0", "id": req_id,',
            '            "result": {',
            '                "protocolVersion": "2024-11-05",',
            '                "capabilities": {"tools": {"listChanged": False}},',
            f'                "serverInfo": {{"name": "{server_name}", "version": "1.0.0"}}',
            '            }',
            '        }',
            '    elif method == "tools/list":',
            '        return {"jsonrpc": "2.0", "id": req_id, "result": {"tools": TOOLS_SCHEMA}}',
            '    elif method == "tools/call":',
            '        t_name = params.get("name")',
            '        args = params.get("arguments", {})',
            '        try:',
        ])

        # Tool dispatcher if/elif
        for idx, tool in enumerate(tools):
            cond = "if" if idx == 0 else "elif"
            template_parts.append(f'            {cond} t_name == "{tool.name}":')
            template_parts.append(f"                res = {tool.name}(**args)")
        template_parts.extend([
            '            else:',
            '                return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -32601, "message": f"Tool \'{t_name}\' not found"}}',
            '            return {"jsonrpc": "2.0", "id": req_id, "result": {"content": [{"type": "text", "text": str(res)}], "isError": False}}',
            '        except Exception as e:',
            '            return {"jsonrpc": "2.0", "id": req_id, "result": {"content": [{"type": "text", "text": f"Error: {e}"}], "isError": True}}',
            '    return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -32601, "message": "Method not found"}}',
            '',
            'def main():',
            '    for line in sys.stdin:',
            '        if not line.strip(): continue',
            '        try:',
            '            req = json.loads(line)',
            '            resp = handle_message(req)',
            '            sys.stdout.write(json.dumps(resp) + "\\n")',
            '            sys.stdout.flush()',
            '        except Exception as e:',
            '            sys.stderr.write(f"Protocol Error: {e}\\n")',
            '',
            'if __name__ == "__main__":',
            '    main()',
        ])

        final_script = "\n".join(template_parts)

        if output_file_path:
            os.makedirs(os.path.dirname(os.path.abspath(output_file_path)), exist_ok=True)
            with open(output_file_path, "w", encoding="utf-8") as f:
                f.write(final_script)

        return final_script
