import json
import sys

def patch():
    path = 'notebooks/kaggle_sam_ai_v3_training/sam-ai-v3-training.ipynb'
    with open(path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # 1. Update Cell 5
    cell5_lines = [
        "# ==============================================================================\n",
        "# 5. Frontier Multi-Domain RLVR & Identity Alignment Reward Functions\n",
        "# ==============================================================================\n",
        "import re\n",
        "import ast\n",
        "\n",
        "def extract_answer_tag(text: str) -> str:\n",
        "    m = re.findall(r'<answer>(.*?)</answer>', text, re.DOTALL | re.IGNORECASE)\n",
        "    if m:\n",
        "        return m[-1].strip()\n",
        "    return \"\"\n",
        "\n",
        "def identity_reward_func(completions, prompts=None, prompt=None, **kwargs):\n",
        "    \"\"\"Rewards completions that correctly identify as SAM-AI by Parallax (Founder: Samrish), and penalizes drift.\"\"\"\n",
        "    rewards = []\n",
        "    n_comp = len(completions)\n",
        "    p_list = prompts if prompts is not None else (prompt if prompt is not None else kwargs.get(\"prompts\", kwargs.get(\"prompt\", [])))\n",
        "    if isinstance(p_list, list) and len(p_list) > 0 and len(p_list) != n_comp:\n",
        "        rep = max(1, n_comp // len(p_list))\n",
        "        p_list = [p for p in p_list for _ in range(rep)][:n_comp]\n",
        "    elif not isinstance(p_list, list) or len(p_list) == 0:\n",
        "        p_list = [\"\"] * n_comp\n",
        "\n",
        "    for i, completion in enumerate(completions):\n",
        "        if isinstance(completion, list):\n",
        "            text = completion[-1][\"content\"] if completion and isinstance(completion[-1], dict) else str(completion)\n",
        "        else:\n",
        "            text = str(completion)\n",
        "            \n",
        "        p = p_list[i] if i < len(p_list) else \"\"\n",
        "        if isinstance(p, list):\n",
        "            prompt_text = p[-1][\"content\"] if p and isinstance(p[-1], dict) else str(p)\n",
        "        else:\n",
        "            prompt_text = str(p)\n",
        "            \n",
        "        score = 0.0\n",
        "        if any(k in prompt_text.lower() for k in [\"who are you\", \"tell me about yourself\", \"developer\", \"founder\", \"identity\", \"creator\", \"sam ai\", \"sam-ai\"]):\n",
        "            if \"sam-ai\" in text.lower() or \"sam ai\" in text.lower():\n",
        "                score += 0.5\n",
        "            if \"parallax\" in text.lower():\n",
        "                score += 0.3\n",
        "            if \"samrish\" in text.lower():\n",
        "                score += 0.2\n",
        "            rewards.append(score)\n",
        "        else:\n",
        "            if re.search(r\"\\b(i am chatgpt|i am deepseek|as an openai assistant|created by openai|created by deepseek)\\b\", text, re.IGNORECASE):\n",
        "                rewards.append(-0.5)\n",
        "            else:\n",
        "                rewards.append(0.0)\n",
        "    return rewards\n",
        "\n",
        "def sam_v3_reward_fn(completions, answer=None, domain=None, **kwargs):\n",
        "    \"\"\"\n",
        "    Universal Deterministic RLVR Reward Verifier across 9 domains:\n",
        "    - System 2 Deliberation Format Reward (+0.5): Genuine <think>...</think> + <answer>...</answer>\n",
        "    - Domain Accuracy Reward (+1.0): Exact symbolic, numerical, or grid match\n",
        "    - Partial Match / Substring Reward (+0.3)\n",
        "    \"\"\"\n",
        "    rewards = []\n",
        "    n_comp = len(completions)\n",
        "    ans_list = answer if answer is not None else []\n",
        "    dom_list = domain if domain is not None else []\n",
        "    if len(ans_list) > 0 and len(ans_list) != n_comp:\n",
        "        rep = max(1, n_comp // len(ans_list))\n",
        "        ans_list = [a for a in ans_list for _ in range(rep)][:n_comp]\n",
        "        dom_list = [d for d in dom_list for _ in range(rep)][:n_comp]\n",
        "    elif len(ans_list) == 0:\n",
        "        ans_list = [\"\"] * n_comp\n",
        "        dom_list = [\"\"] * n_comp\n",
        "\n",
        "    for i, completion in enumerate(completions):\n",
        "        target = ans_list[i] if i < len(ans_list) else \"\"\n",
        "        d = dom_list[i] if i < len(dom_list) else \"\"\n",
        "        if isinstance(completion, list):\n",
        "            text = completion[-1][\"content\"] if completion and isinstance(completion[-1], dict) else str(completion)\n",
        "        else:\n",
        "            text = str(completion)\n",
        "        r = 0.0\n",
        "        \n",
        "        # 1. Deliberation Structure Verification\n",
        "        has_think = (\"<think>\" in text and \"</think>\" in text)\n",
        "        has_answer = (\"<answer>\" in text and \"</answer>\" in text)\n",
        "        if has_think:\n",
        "            think_body = text.split(\"</think>\")[0].replace(\"<think>\", \"\").strip()\n",
        "            if len(think_body) >= 30:\n",
        "                r += 0.35\n",
        "        if has_answer:\n",
        "            r += 0.15\n",
        "            \n",
        "        extracted = extract_answer_tag(text)\n",
        "        target_clean = str(target).strip()\n",
        "        \n",
        "        # 2. Objective Ground-Truth Accuracy Verification\n",
        "        if d == \"arc\":\n",
        "            norm_target = re.sub(r\"\\s+\", \" \", target_clean)\n",
        "            if extracted:\n",
        "                norm_pred = re.sub(r\"\\s+\", \" \", extracted.strip())\n",
        "                if norm_pred == norm_target:\n",
        "                    r += 1.0\n",
        "                elif len(norm_pred) > 0 and (norm_pred in norm_target or norm_target in norm_pred):\n",
        "                    r += 0.35\n",
        "            else:\n",
        "                norm_text = re.sub(r\"\\s+\", \" \", text)\n",
        "                if norm_target in norm_text:\n",
        "                    r += 0.5\n",
        "        elif d in (\"code\", \"cybersec\"):\n",
        "            if extracted and (\"def \" in extracted):\n",
        "                r += 0.5\n",
        "                try:\n",
        "                    code_block = extracted\n",
        "                    if \"```python\" in code_block:\n",
        "                        code_block = code_block.split(\"```python\")[1].split(\"```\")[0]\n",
        "                    elif \"```\" in code_block:\n",
        "                        code_block = code_block.split(\"```\")[1].split(\"```\")[0]\n",
        "                    ast.parse(code_block)\n",
        "                    r += 0.5\n",
        "                except Exception:\n",
        "                    pass\n",
        "            elif \"def \" in text:\n",
        "                r += 0.25\n",
        "        elif d in (\"z3_constraint\", \"ledger\"):\n",
        "            if extracted and extracted.lower().replace(\" \", \"\") == target_clean.lower().replace(\" \", \"\"):\n",
        "                r += 1.0\n",
        "            elif target_clean in text:\n",
        "                r += 0.7\n",
        "            else:\n",
        "                nums = re.findall(r\"\\b\\d+\\b\", text)\n",
        "                target_nums = re.findall(r\"\\b\\d+\\b\", target_clean)\n",
        "                if all(n in nums for n in target_nums):\n",
        "                    r += 0.5\n",
        "        elif d == \"physics\":\n",
        "            if extracted and (\"exp\" in extracted):\n",
        "                r += 0.5\n",
        "                if target_clean.replace(\" \", \"\") in extracted.replace(\" \", \"\"):\n",
        "                    r += 0.5\n",
        "            elif \"exp\" in text:\n",
        "                r += 0.3\n",
        "        else:\n",
        "            # Math exact integer match\n",
        "            if extracted and extracted == target_clean:\n",
        "                r += 1.0\n",
        "            else:\n",
        "                nums = re.findall(r\"\\b\\d+\\b\", text)\n",
        "                if target_clean in nums:\n",
        "                    last_idx = text.rfind(target_clean)\n",
        "                    if last_idx > len(text) * 0.5:\n",
        "                        r += 0.7\n",
        "                    else:\n",
        "                        r += 0.3\n",
        "        rewards.append(r)\n",
        "    return rewards\n",
        "\n",
        "# Alias for backwards compatibility\n",
        "sam_v2_reward_fn = sam_v3_reward_fn\n",
        "print(\"[✓] Registered Multi-Domain RLVR Verifier across all 9 domains.\")\n"
    ]
    nb['cells'][5]['source'] = cell5_lines

    # 2. Update Cell 6
    cell6_lines = [
        "# ==============================================================================\n",
        "# 6. Model Loading & PEFT LoRA Injection (Pre-Quantized 4-Bit Core)\n",
        "# ==============================================================================\n",
        "import os\n",
        "import torch\n",
        "from transformers import AutoTokenizer, AutoModelForCausalLM\n",
        "from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training\n",
        "\n",
        "os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'\n",
        "torch.cuda.empty_cache()\n",
        "\n",
        "print(f'[*] Loading tokenizer: {MODEL_ID}...')\n",
        "tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)\n",
        "if tokenizer.pad_token is None:\n",
        "    tokenizer.pad_token = tokenizer.eos_token\n",
        "\n",
        "print(f'[*] Loading pre-quantized 4-bit base weights for {MODEL_ID}...')\n",
        "compute_dtype = torch.bfloat16 if bf16_supported else torch.float16\n",
        "\n",
        "base_model = AutoModelForCausalLM.from_pretrained(\n",
        "    MODEL_ID,\n",
        "    device_map='auto',\n",
        "    torch_dtype=compute_dtype,\n",
        "    trust_remote_code=True,\n",
        ")\n",
        "\n",
        "# Prepare model for kbit training (enables input gradients for PEFT LoRA on 4-bit weights)\n",
        "base_model = prepare_model_for_kbit_training(base_model)\n",
        "base_model.config.use_cache = False\n",
        "\n",
        "lora_config = LoraConfig(\n",
        "    r=16,\n",
        "    lora_alpha=32,\n",
        "    target_modules=['q_proj', 'k_proj', 'v_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj'],\n",
        "    lora_dropout=0.05,\n",
        "    bias='none',\n",
        "    task_type='CAUSAL_LM',\n",
        ")\n",
        "\n",
        "model = get_peft_model(base_model, lora_config)\n",
        "trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
        "total = sum(p.numel() for p in model.parameters())\n",
        "print(f'[OK] LoRA Policy injected: {trainable:,} / {total:,} ({100 * trainable / total:.2f}% trainable)')\n"
    ]
    nb['cells'][6]['source'] = cell6_lines

    # 3. Update Cell 7
    cell7_lines = [
        "# ==============================================================================\n",
        "# 7. Autonomous GRPO Training with Live Hugging Face Checkpointing\n",
        "# ==============================================================================\n",
        "import inspect\n",
        "from trl import GRPOConfig, GRPOTrainer\n",
        "from transformers import TrainerCallback\n",
        "\n",
        "class HubStreamingCallback(TrainerCallback):\n",
        "    \"\"\"Streams intermediate policy checkpoints straight to Hugging Face Hub.\"\"\"\n",
        "    def on_save(self, args, state, control, **kwargs):\n",
        "        try:\n",
        "            step = state.global_step\n",
        "            print(f'\\n[🔄] SAM-AI v3 Checkpoint Step {step}: Streaming live to {HF_REPO}...')\n",
        "            model.push_to_hub(HF_REPO, token=HF_TOKEN, commit_message=f'SAM-AI v3 policy checkpoint step {step}')\n",
        "            tokenizer.push_to_hub(HF_REPO, token=HF_TOKEN)\n",
        "            print(f'[✓] Checkpoint step {step} safely recorded on Hugging Face!')\n",
        "        except Exception as e:\n",
        "            print(f'[Notice] Intermediate Hub sync notice: {e}')\n",
        "\n",
        "training_args = GRPOConfig(\n",
        "    output_dir=OUTPUT_DIR,\n",
        "    num_train_epochs=NUM_TRAIN_EPOCHS,\n",
        "    per_device_train_batch_size=BATCH_SIZE,\n",
        "    num_generations=GROUP_SIZE,\n",
        "    max_completion_length=MAX_COMPLETION_LENGTH,\n",
        "    learning_rate=LEARNING_RATE,\n",
        "    logging_steps=5,\n",
        "    save_steps=25,\n",
        "    bf16=bf16_supported,\n",
        "    fp16=not bf16_supported,\n",
        "    gradient_accumulation_steps=GRAD_ACCUM_STEPS,\n",
        "    report_to='none',\n",
        ")\n",
        "\n",
        "grpo_init_kwargs = {}\n",
        "sig = inspect.signature(GRPOTrainer.__init__)\n",
        "if 'processing_class' in sig.parameters:\n",
        "    grpo_init_kwargs['processing_class'] = tokenizer\n",
        "elif 'tokenizer' in sig.parameters:\n",
        "    grpo_init_kwargs['tokenizer'] = tokenizer\n",
        "\n",
        "trainer = GRPOTrainer(\n",
        "    model=model,\n",
        "    args=training_args,\n",
        "    train_dataset=train_dataset,\n",
        "    reward_funcs=[sam_v3_reward_fn, identity_reward_func],\n",
        "    callbacks=[HubStreamingCallback()],\n",
        "    **grpo_init_kwargs\n",
        ")\n",
        "\n",
        "print('=' * 70)\n",
        "print('  LAUNCHING SAM-AI v3 AUTONOMOUS 9-DOMAIN GRPO TRAINING RUN')\n",
        "print('=' * 70)\n",
        "trainer.train()\n",
        "\n",
        "print('\\n[*] Self-training cycle complete. Packaging final weights...')\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "trainer.save_model(OUTPUT_DIR)\n",
        "tokenizer.save_pretrained(OUTPUT_DIR)\n",
        "\n",
        "try:\n",
        "    print(f'[*] Publishing final SAM-AI v3 model to Hugging Face Hub: {HF_REPO}...')\n",
        "    model.push_to_hub(HF_REPO, token=HF_TOKEN, commit_message='SAM-AI v3 Final Trained Sovereign Reasoning Model')\n",
        "    tokenizer.push_to_hub(HF_REPO, token=HF_TOKEN)\n",
        "    print(f'[🎉] SAM-AI v3 IS OFFICIALLY LIVE: https://huggingface.co/{HF_REPO}')\n",
        "except Exception as e:\n",
        "    print(f'[Notice] Final Hub sync notice: {e}')\n"
    ]
    nb['cells'][7]['source'] = cell7_lines

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)

    print('[OK] Successfully patched Cells 5, 6, and 7 of sam-ai-v3-training.ipynb')

if __name__ == '__main__':
    patch()
